// <auto-generated />
namespace HiveProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GetUsers_SP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetUsers_SP));
        
        string IMigrationMetadata.Id
        {
            get { return "201903291833087_GetUsers_SP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
