// <auto-generated />
namespace HiveProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangingPrecision_AddingBio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangingPrecision_AddingBio));
        
        string IMigrationMetadata.Id
        {
            get { return "201904021433215_ChangingPrecision_AddingBio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
